# 数据源配置
data_source:
  # 选择数据源类型
  # - "akshare": 适用于A股、ETF数据，免费且无需注册
  # - "tushare": 适用于A股数据，需要注册获取token
  # - "binance": 适用于加密货币数据，需要API密钥
  type: "akshare"
  
  # AKShare配置
  akshare:
    # 市场类型：A股、ETF、期货等
    # - "A股": 适用于股票
    # - "ETF": 适用于ETF基金
    # - "期货": 适用于期货合约
    market: "A股"
  
  # TuShare配置
  tushare:
    # TuShare API token，需要在 tushare.pro 注册获取
    token: "your_tushare_token"
  
  # Binance配置
  binance:
    # 币安API密钥，需要在币安官网申请
    api_key: "your_api_key"
    api_secret: "your_api_secret"

# 策略参数配置
strategy:
  # 短期均线周期，用于生成交易信号
  # 建议范围：5-20，较小值对市场反应更敏感
  short_window: 5
  
  # 长期均线周期，用于确认趋势
  # 建议范围：20-60，较大值可以过滤短期波动
  long_window: 20
  
  # 止损比例，触发后自动平仓
  # 建议范围：0.02-0.05 (2%-5%)，根据风险承受能力设置
  stop_loss: 0.05
  
  # 止盈比例，触发后自动平仓
  # 建议范围：0.05-0.10 (5%-10%)，根据市场波动性设置
  take_profit: 0.10
  
  # 初始资金，回测起始资金量
  initial_capital: 100000
  
  # 基础仓位配置
  base_holding:
    # 是否保持基础仓位
    enabled: true
    # 基础仓位比例（建议 0.2-0.3，即 20%-30%）
    ratio: 0.3
    # 是否在信号出现时动态调整基础仓位
    dynamic_adjust: true
  
  # 仓位管理配置
  position_management:
    # 仓位管理策略类型
    # - "fixed": 固定比例策略，每次交易使用固定比例资金
    # - "dynamic": 动态仓位策略，根据市场状况调整仓位
    # - "kelly": 凯利公式策略，根据胜率动态调整
    # - "batch": 分批建仓策略，分多次建立仓位
    type: "dynamic"
    
    # 基础仓位比例，作为仓位计算的基准
    # 建议范围：0.2-0.4，保守型投资者建议使用较小值
    base_position: 0.4
    
    # 最大仓位比例，账户整体仓位上限
    # 建议范围：0.5-0.8，建议预留部分资金应对波动
    max_position: 0.9
    
    # 分批建仓配置（仅在 type="batch" 时使用）
    # 示例：分三次买入，每次使用40%、30%、30%的计划投入资金
    batch_sizes: [0.4, 0.3, 0.3]
    # 每次买入的间隔天数
    batch_delays: [0, 2, 5]

# 交易标的代码
# A股ETF示例：
# - "sh510300": 沪深300ETF（上证）
# - "sz159919": 沪深300ETF（深证）
# - "sh510500": 中证500ETF
# - "sh510050": 上证50ETF
# - "sz159915": 创业板ETF
symbol: "sz159919"

# 回测起始日期
# 格式：YYYY-MM-DD
start_time: "2023-01-01"

# 回测结束日期
# 格式：YYYY-MM-DD
end_time: "2025-02-01"

# 数据周期
# 可选值：
# - "1m": 1分钟，适用于日内交易
# - "5m": 5分钟，适用于日内交易
# - "15m": 15分钟，适用于日内交易
# - "30m": 30分钟，适用于日内交易
# - "1h": 1小时，适用于日内交易
# - "1d": 日线（推荐），适用于中长期投资
# - "1w": 周线，适用于长期投资
# - "1M": 月线，适用于超长期投资
interval: "1d"

# 基准配置
benchmark:
  # 主基准（当前交易的标的）
  primary: "sz159919"  # 当前交易的ETF
  # 市场基准
  market:
    - symbol: "sh000001"  # 上证指数
      name: "上证指数"
    - symbol: "sh000300"  # 沪深300
      name: "沪深300" 